### PR TITLE
python2 and python3 compatibility

### PR DESCRIPTION
**Pull request by a358003542**

### CODE REVIEW

**Comment by vadmium** [comment]
What problem are you tring to solve? The SocketKind enum classes were added in Python 3.4, but the plain socket.SOCK_STREAM, etc constants are still available. I don’t understand what benefit this change would bring.

**Comment by a358003542** [comment]
The https url link in python3 and the original code cannot work out .it mainly because of the module change in python3. 发自网易邮箱大师 On 2015-10-17 07:50 , Martin Panter Wrote: What problem are you tring to solve? The SocketKind enum classes were added in Python 3.4, but the plain socket.SOCK_STREAM, etc constants are still available. I don’t understand what benefit this change would bring. — Reply to this email directly or view it on GitHub.

**Comment by Anorov** [comment]
I also do not understand this. `socket.SOCK_STREAM` is just an alias for `socket.SocketKind.SOCK_STREAM` in Python 3.4 and up.

**Comment by a358003542** [comment]
this is the test code 
```python
import socket
import socks
SOCKS5_PROXY_HOST = '127.0.0.1'
SOCKS5_PROXY_PORT = 1080
socks.set_default_proxy(socks.SOCKS5, SOCKS5_PROXY_HOST, SOCKS5_PROXY_PORT)
socket.socket = socks.socksocket


import requests
print(requests.get('https://www.google.com', timeout=24).text)
```
and for original code will raise this error:

```
    raise ValueError(msg.format(type))
ValueError: Socket type must be stream or datagram, not 2049
>>> 
```
and if the URL scheme is http , then there will be no error raised.
-------
sorry for my mistake, and i modified the code like this pull requests, but it aslo cannot work fine. it turn out that only commented that line can works fine for the https scheme .

i can not figure it out now , you guys have ideas ?

**Comment by vadmium** [comment]
My guess is you are using Linux and something in Requests is trying to make a socket using the new SOCK_NONBLOCK flag:

```python
>>> s = socket()
>>> s.type
<SocketKind.SOCK_STREAM: 1>
>>> s.settimeout(24)
>>> s.type
2049
>>> s.close()
>>> s = socket(type=SOCK_STREAM | SOCK_NONBLOCK)
>>> s.type
2049
>>> s.gettimeout()  # Zero apparently means non-blocking mode
0.0
```

**Comment by Anorov** [comment]
Closing this issue as it does not appear to be related to PySocks.

**Pull request closed without merging**
